# Generated by Django 5.0.6 on 2024-07-07 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0003_poll_total_votes"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="poll",
            name="total_votes",
        ),
    ]
