# Generated by Django 5.0.6 on 2024-07-07 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0005_votemodel_remove_choice_votes"),
    ]

    operations = [
        migrations.AddField(
            model_name="votemodel",
            name="choice",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to="poll.choice",
            ),
            preserve_default=False,
        ),
    ]
