# Generated by Django 5.0.6 on 2024-07-07 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0006_votemodel_choice"),
    ]

    operations = [
        migrations.AddField(
            model_name="choice",
            name="votes",
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name="voteModel",
        ),
    ]
