# Generated by Django 5.0.6 on 2024-07-07 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("poll", "0007_choice_votes_delete_votemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="choice",
            name="choice_text",
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
